// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://chaowovbgkifxuaqsvlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoYW93b3ZiZ2tpZnh1YXFzdmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTYxMDMsImV4cCI6MjA2NTgzMjEwM30.bQeK9Mf1_iLdkW9XJFDynR-iyCdadDpgaP6YofA25hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);